memory_limit = 512M
upload_max_filesize = 20M
post_max_size = 25M
date.timezone = Europe/Paris
expose_php = Off

opcache.enable = 1
opcache.memory_consumption = 256
opcache.max_accelerated_files = 20000
; En dev, les fichiers sont revalidés à chaque requête
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0

realpath_cache_size = 4096K
realpath_cache_ttl = 600
